git:
  branch: master

target_port: 8000

wants:
  postgres: true

secrets:
  - SECRET_KEY
  - GROUND_TRUTH_CLIENT_ID
  - GROUND_TRUTH_CLIENT_SECRET

files:
  /etc/piranha:
    secret: true
    contents:
      google_application_credentials.json:
        env: GOOGLE_APPLICATION_CREDENTIALS

env:
  GROUND_TRUTH_URL: https://login.hack.gt
  DEBUG: false
  TIME_ZONE: America/New_York
  PRODUCTION: true
  GOOGLE_STORAGE_BUCKET: piranha-uploads
