git:
  branch: master

wants:
  postgres: true

health:
  path: /status

secrets:
  - SESSION_SECRET
  - GROUND_TRUTH_ID
  - GROUND_TRUTH_SECRET
  - SLACK_API_TOKEN

files:
  /etc/piranha:
    secret: true
    contents:
      google-application-key.json:
        env: GOOGLE_APPLICATION_CREDENTIALS

env:
  GROUND_TRUTH_URL: https://login.hack.gt
  DEBUG: false
  TIME_ZONE: America/New_York
  PRODUCTION: true
  GOOGLE_STORAGE_BUCKET: piranha-uploads
  ADMIN_ALERT_CHANNEL: finance-alerts
