git:
  branch: master

target_port: 3000

wants:
  postgres: true

secrets:
  - SESSION_SECRET
  - GROUND_TRUTH_CLIENT_ID
  - GROUND_TRUTH_CLIENT_SECRET
  - SLACK_API_TOKEN

files:
  /etc/piranha:
    secret: true
    contents:
      google-application-key.json:
        env: GOOGLE_APPLICATION_CREDENTIALS

env:
  GROUND_TRUTH_URL: https://login.hack.gt
  DEBUG: false
  TIME_ZONE: America/New_York
  PRODUCTION: true
  GOOGLE_STORAGE_BUCKET: piranha-uploads
