git:
  branch: master

target_port: 8000

wants:
  postgres: true

secrets:
  - SECRET_KEY
  - GROUND_TRUTH_CLIENT_ID
  - GROUND_TRUTH_CLIENT_SECRET

env:
  GROUND_TRUTH_URL: https://login.hack.gt
  DEBUG: false
  TIME_ZONE: America/New_York