# Generated by Django 3.0.4 on 2020-03-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_code',
            field=models.CharField(default='', help_text='A short, 2-5 character code to represent this project',
                                   max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='reference_id',
            field=models.CharField(db_index=True, default='', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
