# Generated by Django 3.0.4 on 2020-03-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0002_auto_20200319_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='approval',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Requisition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='is_approving',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(
                help_text='The year of the end date will be used to abbreviate this fiscal year in requisition     reference IDs'),
        ),
    ]
