# Generated by Django 3.0.4 on 2020-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0003_auto_20200319_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='project_requisition_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
