# Generated by Django 3.0.4 on 2020-03-21 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0004_requisition_project_requisition_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'permissions': (('can-edit-locked-requisition', 'Can edit locked requisitions'),
                                     ('can-edit-unlocked-requisition', 'Can edit unlocked requisitions'))},
        ),
    ]
