# Generated by Django 3.0.4 on 2020-03-21 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0005_auto_20200320_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={},
        ),
    ]
