# Generated by Django 3.0.4 on 2020-03-24 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0006_auto_20200321_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Created at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Updated at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='Created at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='Updated at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Created at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Updated at',
            new_name='updated_at',
        ),
    ]
