# Generated by Django 3.0.4 on 2020-04-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0008_auto_20200429_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
