# Generated by Django 3.0.4 on 2020-04-29 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0009_paymenttype_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='recipient_object_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recipient_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='expenses.Vendor'),
            preserve_default=False,
        ),
    ]
