# Generated by Django 3.0.4 on 2020-04-29 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0010_auto_20200429_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentType',
            new_name='PaymentMethod',
        ),
    ]
