# Generated by Django 3.0.4 on 2020-05-07 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20200429_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fiscal_year',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FiscalYear',
        ),
    ]
