# Generated by Django 3.0.4 on 2020-06-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_auto_20200507_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='point_of_contact',
        ),
    ]
