# Generated by Django 3.0.4 on 2020-06-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_remove_requisition_point_of_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionitem',
            old_name='short_name',
            new_name='name',
        ),
    ]
