# Generated by Django 3.0.4 on 2020-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_auto_20200604_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='other_fees',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
