# Generated by Django 3.0.7 on 2020-07-02 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_requisition_other_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='other_fees',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='payment_required_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Pending Changes', 'Pending Changes'), ('Ready to Order', 'Ready to Order'), ('Ordered', 'Ordered'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.Vendor'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
