# Generated by Django 3.0.7 on 2020-07-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_auto_20200701_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
