# Generated by Django 3.0.7 on 2020-07-12 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_auto_20200701_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='friendly_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
