# Generated by Django 3.0.7 on 2020-07-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_auto_20200712_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='is_approving',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
