# Generated by Django 3.0.7 on 2020-07-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_auto_20200712_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='payment_required_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
