# Generated by Django 3.0.7 on 2020-07-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_auto_20200713_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
