# Generated by Django 3.0.7 on 2020-07-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_requisitionitem_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Pending Changes', 'Pending Changes'), ('Ready to Order', 'Ready to Order'), ('Ordered', 'Ordered'), ('Partly Received', 'Partly Received'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
    ]
