# Generated by Django 3.0.7 on 2020-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_auto_20200714_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='shipping_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
