# Generated by Django 3.0.7 on 2020-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_requisition_shipping_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='shipping_location',
        ),
        migrations.AddField(
            model_name='payment',
            name='shipping_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
