# Generated by Django 3.0.7 on 2020-07-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_auto_20200714_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='requisition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenses.Requisition'),
        ),
    ]
