# Generated by Django 3.0.7 on 2020-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_auto_20200714_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='shipping_location',
        ),
        migrations.AddField(
            model_name='requisition',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='shipping_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
