# Generated by Django 3.0.7 on 2020-07-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_permissions_and_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='is_reimbursement',
            field=models.BooleanField(default=False),
        ),
    ]
