# Generated by Django 3.0.7 on 2020-07-25 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_auto_20200724_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='funding_source',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_direct_payment',
            field=models.BooleanField(default=False),
        ),
    ]
