# Generated by Django 3.0.7 on 2020-07-25 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0031_auto_20200724_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='funding_source',
        ),
        migrations.AddField(
            model_name='requisition',
            name='funding_source',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.PaymentMethod'),
        ),
    ]
