# Generated by Django 3.0.7 on 2020-07-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0032_auto_20200724_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Pending Changes', 'Pending Changes'), ('Ready to Order', 'Ready to Order'), ('Ordered', 'Ordered'), ('Partially Received', 'Partially Received'), ('Received', 'Received'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Ready for Reimbursement', 'Ready for Reimbursement'), ('Awaiting Information', 'Awaiting Information'), ('Reimbursement in Progress', 'Reimbursement in Progress')], default='Draft', max_length=50),
        ),
    ]
