# Generated by Django 3.0.7 on 2020-07-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0034_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='text/plain', max_length=50),
            preserve_default=False,
        ),
    ]
