# Generated by Django 3.0.7 on 2020-08-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20200806_2322'),
        ('expenses', '0035_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgets.Budget'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budgets.LineItem'),
        ),
    ]
