# Generated by Django 3.0.7 on 2020-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0036_auto_20200806_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
