# Generated by Django 3.1.2 on 2020-10-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0037_requisition_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.vendor'),
        ),
    ]
