# Generated by Django 3.1.2 on 2020-10-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0038_requisitionitem_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='recipient',
        ),
    ]
