# Generated by Django 3.1.2 on 2020-10-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0039_remove_payment_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='link',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
