# Generated by Django 3.0.4 on 2020-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seaport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
