# Generated by Django 3.0.7 on 2020-08-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaport', '0003_auto_20200318_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
