# Generated by Django 3.1.2 on 2020-10-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaport', '0004_user_slack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
