# Generated by Django 3.0.7 on 2020-08-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='budget_content_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='budget_object_id',
        ),
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budgets.Budget'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OperatingLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('operating_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.OperatingBudget')),
            ],
        ),
    ]
